### ISSUE TITLE
raml file not parsable

### ISSUE THREAD

**Issue by aitorhh** [edgexfoundry/export-client#21]
I cannot parse `export-client.raml` using, for example https://github.com/raml-org/raml-js-parser or postman. This [line](https://github.com/edgexfoundry/export-client/blob/7a63132c7b0e58c225ddec1d6dc3ced06364c895/src/test/resources/raml/export-client.raml#L129)

            description: Export Client registration property type. Valid types are: "algorithms", "compressions", "formats", and "destinations".

gives an error due to the quotes`" "`, It could just be solved by wrapping the string with single quotes `'Export ...'`.

The file doesn't seem to be generated automatically, but, just in case I don't provide a PR, just this change.

**Comment by jpwhitemn** [comment]
@brandonforster please check this is still issue

**Comment by jpwhitemn** [comment]
@brandonforster  please check this is still an issue

**Comment by eb-oss** [comment]
Closing this issue; project is being archived.
